service: notify-slack

provider:
  name: aws
  region: ${env:REGION, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  memorySize: 256

custom:
  esbuild:
    bundle: true
    minify: false

plugins:
  - serverless-esbuild

package:
  individually: true

functions:
  notify:
    handler: functions/index.handler
    name: notify-slack-demo-${self:provider.stage}
    events:
      - http:
          path: /notify
          method: get
    environment:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      SLACK_CHANNEL_NAME: aws-lambda
